enableScripts: false
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-prebuilds.js
    spec: .yarn/plugins/@yarnpkg/plugin-prebuilds.js
  - path: .yarn/plugins/@yarnpkg/plugin-redirect-app-builder.js
    spec: "https://raw.githubusercontent.com/electricui/yarn-redirect-app-builder/master/bundles/%40yarnpkg/plugin-redirect-app-builder.js"
npmScopes:
  electricui:
    npmRegistryServer: 'https://registry.eui.io/'
prebuildHostMirrorTemplate: '{mirror_url}/{scopeWithAtAndSlash}{name}-v{version}-{runtime}-v{abi}-{platform}{libc}-{arch}.tar.gz'
prebuildHostMirrorUrl: 'https://registry.eui.io/prebuilds'
packageExtensions:
  chokidar@*:
    dependencies:
      fsevents: 2.1.3
  debug@*:
    dependencies:
      supports-color: 7.1.0
